groups:
  - name: fame-training-alerts
    interval: 1m
    rules:
      - alert: TrainingRewardDrop
        expr: training_policy_reward_avg < 0.2
        for: 10m
        labels:
          severity: warning
          component: training
        annotations:
          summary: "Training reward dropping"
          description: "Average training reward {{ $value }} fell below 0.2 for 10 minutes."

      - alert: TrainingWinRateCritical
        expr: training_policy_win_rate < 0.4
        for: 5m
        labels:
          severity: critical
          component: training
        annotations:
          summary: "Training win rate critical"
          description: "Training win rate {{ $value }} fell below 40%."

      - alert: TrainingDriftSpike
        expr: rate(training_policy_drift_score_sum[15m]) / clamp_min(rate(training_policy_drift_score_count[15m]), 1) > 0.5
        for: 10m
        labels:
          severity: warning
          component: training
        annotations:
          summary: "Training drift spike detected"
          description: "Average drift score exceeded 0.5. Investigate data distribution shift."

      - alert: TrainingLatencyHigh
        expr: histogram_quantile(0.95, rate(training_policy_latency_ms_bucket[10m])) > 5000
        for: 10m
        labels:
          severity: warning
          component: training
        annotations:
          summary: "Training latency elevated"
          description: "95th percentile training latency exceeded 5 seconds."

      - alert: ExperienceBufferStall
        expr: rate(training_experience_buffer_size[10m]) == 0
        for: 30m
        labels:
          severity: warning
          component: training
        annotations:
          summary: "Experience buffer not growing"
          description: "Experience buffer size unchanged for 30 minutes. Check telemetry ingestion."

